import type { TimelineEntry } from "./types";

export const seedTimelineEntries: TimelineEntry[] = [
  {
    id: "seed-2025-jee-restart",
    slug: "jee-restart",
    title: "JEE Restart",
    date: "2025-01-01",
    year: "2025",
    summary: "A return to fundamentals and a cleaner study rhythm.",
    category: "Study chapter",
    coverImageUrl: "",
    href: "/now",
    accent: "#9A8A5A",
    word: "STUDY",
    status: "Active",
  },
  {
    id: "seed-2026-hisarchives-launch",
    slug: "hisarchives-launch",
    title: "HisArchives Launch",
    date: "2026-06-04",
    year: "2026",
    summary: "The archive gets a public home and a stable identity.",
    category: "Archive opening",
    coverImageUrl: "",
    href: "/archives/hisarchives",
    accent: "#28325A",
    word: "SITE",
    status: "Active",
  },
  {
    id: "seed-2026-automation-systems",
    slug: "automation-systems",
    title: "Automation Systems",
    date: "2026-08-01",
    year: "2026",
    summary: "Small systems start carrying real weight.",
    category: "Build chapter",
    coverImageUrl: "",
    href: "/archives/discord-automation",
    accent: "#4D6A8E",
    word: "CODE",
    status: "Active",
  },
  {
    id: "seed-2026-fitness-journey",
    slug: "fitness-journey",
    title: "Fitness Journey",
    date: "2026-10-01",
    year: "2026",
    summary: "Consistency becomes a logged practice.",
    category: "Body record",
    coverImageUrl: "",
    href: "/archives/fitness",
    accent: "#66785A",
    word: "FIT",
    status: "Active",
  },
  {
    id: "seed-2027-jee-attempt",
    slug: "jee-attempt",
    title: "JEE Attempt",
    date: "2027-04-01",
    year: "2027",
    summary: "The main academic attempt arrives.",
    category: "Primary milestone",
    coverImageUrl: "",
    href: "/archives/jee-2027",
    accent: "#A08A44",
    word: "JEE",
    status: "Active",
  },
  {
    id: "seed-2031-btech-completion",
    slug: "btech-completion",
    title: "BTech Completion",
    date: "2031-06-01",
    year: "2031",
    summary: "A longer arc for the record.",
    category: "Degree archive",
    coverImageUrl: "",
    href: "/archives/notes",
    accent: "#7A7F88",
    word: "BTECH",
    status: "Active",
  },
  {
    id: "seed-future-germany-mission",
    slug: "germany-mission",
    title: "Germany Mission",
    date: "2035-01-01",
    year: "Future",
    summary: "A longer-term mission that can collect detail as the timeline advances.",
    category: "Long-range plan",
    coverImageUrl: "",
    href: "/archives/memories",
    accent: "#7B4C57",
    word: "FUTURE",
    status: "Planned",
  },
];
